### ISSUE TITLE
make tax_year_assessment_bins a CSV

### ISSUE THREAD

**Issue by LuckyLaharlTim** [musa-5090-spring-2024/musa5090s24-team2-cama#25]
- [x] Add `tax_year_assessment_bins.sql` branch of `run_sql` to `data_pipeline` Workflow
- [x] create `update_tax_year_assessment_bins` function to google cloud
    - should download the table from BigQuery in <ins>CSV</ins> format & upload to the [`musa5090s24_team02_public`](https://console.cloud.google.com/storage/browser/musa5090s24_team02_public;tab=objects?forceOnBucketsSortingFiltering=true&project=musa509s24-team2) bucket

**Comment by LuckyLaharlTim** [comment]
* is currently a jsonl

**Comment by junyi2022** [comment]
@LuckyLaharlTim Hi! I feel like maybe this part needs to be a CSV instead of JSON because when I work with the front-end part, I can only export the JSONL to CSV manually in order to have something for the front-end's chart setup. (the file ```tax_year_assessment_bins``` in the ```public bucket``` is a CSV right now).  In this way, the front-end code currently works with CSV instead of JSON. FYI I changed this issue into CSV.

**Comment by LuckyLaharlTim** [comment]
@junyi2022 Hi. I've recreated the table and exported `tax_year_assessment_bins` from BigQuery. While the contents are in CSV format, the file is a generic file type, so I also uploaded the same document as a CSV. The name changed to `tax_year_assessment_bins.csv`.  If this is good, feel free to close the issue.

**Comment by junyi2022** [comment]
@LuckyLaharlTim Thank you! It works. But I'm wondering do we need/have a cloud function for this step? Looks like the generation of ```tax_year_assessment_bins``` table in Bigquery is also not in a cloud function.

**Comment by LuckyLaharlTim** [comment]
@junyi2022 It's not currently done at the moment. The `run_sql` function will generate an internal(?) table to bigquery, but the csv will need to be downloaded and then uploaded to google cloud.

I'll add some steps for this in the description, and hopefully we'll get to the uploading script before Wednesday.

**Comment by junyi2022** [comment]
@LuckyLaharlTim FYI I finish the second part of this issue which get the derived table `tax_year_assessment_bins` from bigquery and upload it as csv to the public bucket `musa5090s24_team02_public` in cloud storage. The cloud function is called `export_assessment_data_csv`

**Comment by LuckyLaharlTim** [comment]
**closed with commit https://github.com/musa-5090-spring-2024/musa5090s24-team2-cama/commit/f95e202c8127fd74d010214a35a9e4db19f97d5a**
